name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          appdir: "apps/api"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pvdthings-api-dev"
          heroku_email: ${{secrets.HEROKU_EMAIL}}